### ISSUE TITLE
[BUG] Installation UnsatisfiableError

### ISSUE THREAD

**Issue by tomcohen0079** [Radiomics/pyradiomics#603]
**Describe the bug**
getting the same installation bug on two different systems , mac and windows . i also tried using different python versions 

**bug**
conda install -c radiomics pyradiomics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyradiomics -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.4,<3.5.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**To Reproduce**
conda install -c radiomics pyradiomics

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**

**Comment by jvanlunenburg** [comment]
Have you tried running `conda install python=3.7` first?

**Comment by tomcohen0079** [comment]
> Have you tried running `conda install python=3.7` first?

yes

**Comment by JoostJM** [comment]
Still, your message indicates it tries to install PyRadiomics for python3.8, which is currently not distributed yet. Have you tried pip installing PyRadiomics?

**Comment by tomcohen0079** [comment]
> Still, your message indicates it tries to install PyRadiomics for python3.8, which is currently not distributed yet. Have you tried pip installing PyRadiomics?

this is what i get when i use python 3.7 :

conda install -c radiomics pyradiomics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyradiomics -> python[version='>=3.8,<3.9.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by tomcohen0079** [comment]
> Still, your message indicates it tries to install PyRadiomics for python3.8, which is currently not distributed yet. Have you tried pip installing PyRadiomics?

when i use pip , i get this error:

cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tomcohen/opt/anaconda3/envs/py37/include -arch x86_64 -I/Users/tomcohen/opt/anaconda3/envs/py37/include -arch x86_64 -I/Users/tomcohen/opt/anaconda3/envs/py37/include/python3.7m -I/Users/tomcohen/opt/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/core/include -I/Users/tomcohen/opt/anaconda3/envs/py37/include/python3.7m -c radiomics/src/_cmatrices.c -o build/temp.macosx-10.9-x86_64-3.7/radiomics/src/_cmatrices.o
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
error: command 'gcc' failed with exit status 1

**Comment by JoostJM** [comment]
I've recently made a new release for PyRadiomics, including some new conda installs, this should fix this issue.

**Comment by ShirleyPmy** [comment]
**I ran into the same error. python version = 3.6.**
(python3.6) 84:~ $ conda install -c radiomics pyradiomics
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyradiomics -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by mlewis1973** [comment]
this issue is still an issue. I tried envs with both 3.6 and 3.7 and pyradiomics v3.0.1, v3.0 and 2.2.0. 
The specifications for the python version always look incorrect, even if you tell conda to install the correct build.

(py37) anaconda@sw490145-rad ~ % conda install -c radiomics pyradiomics=v3.0.1=py37_0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyradiomics==v3.0.1=py37_0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by JoostJM** [comment]
version 3.0.1 is currently not available on conda cloud for windows. The coninuous integration is raising some errors that I haven't been able to track down yet. In the meantime, you should be able to install using `pip install pyradiomics`, this should also work on anaconda.

**Comment by helderc** [comment]
@tomcohen0079 did you manage how to install it? I'm having the same issue.

**Comment by ahxmeds** [comment]
Was this resolved? I got the same error while installing it in a `conda` environment with either python 3.6 and 3.7.

**Comment by helderc** [comment]
I was able to install it in Python 3.10 from the sources following this: https://pyradiomics.readthedocs.io/en/latest/installation.html#install-from-source

**Comment by ahxmeds** [comment]
I looked more carefully now. In python=3.6, I am able to install it, since `pip install pyradiomics` gives this: 
```
Requirement already satisfied: pyradiomics in /anaconda/envs/pyrad/lib/python3.6/site-packages (3.0.1)
Requirement already satisfied: six>=1.10.0 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pyradiomics) (1.16.0)
Requirement already satisfied: numpy>=1.9.2 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pyradiomics) (1.19.5)
Requirement already satisfied: pykwalify>=1.6.0 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pyradiomics) (1.8.0)
Requirement already satisfied: SimpleITK>=0.9.1 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pyradiomics) (2.1.1.2)
Requirement already satisfied: PyWavelets>=0.4.0 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pyradiomics) (1.1.1)
Requirement already satisfied: ruamel.yaml>=0.16.0 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pykwalify>=1.6.0->pyradiomics) (0.17.21)
Requirement already satisfied: docopt>=0.6.2 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pykwalify>=1.6.0->pyradiomics) (0.6.2)
Requirement already satisfied: python-dateutil>=2.8.0 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from pykwalify>=1.6.0->pyradiomics) (2.8.2)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /anaconda/envs/pyrad/lib/python3.6/site-packages (from ruamel.yaml>=0.16.0->pykwalify>=1.6.0->pyradiomics) (0.2.7)
```

But when I try `import pyradiomics` in the same conda environment, it gives a `ModuleNotFoundError: No module named 'pyradiomics'`. I set the correct env path too, but that didn't work.

**Comment by ahxmeds** [comment]
> I was able to install it in Python 3.10 from the sources following this: https://pyradiomics.readthedocs.io/en/latest/installation.html#install-from-source

Thanks, @helderc. Regarding installing from the source, I got a `Connection timed out` error when I try to clone the github repo: 
```
Cloning into 'pyradiomics'...
fatal: unable to connect to github.com:
github.com[0: 140.82.114.3]: errno=Connection timed out
```

**Comment by helderc** [comment]
Hi @ahxmeds, this is strange. Maybe your connection is unstable?
